base/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'core.views.home', name='home'),
    url(r'^create_account$', 'core.views.create_account', name='create_account'),

    url(r'^finished/', include('finished.urls')),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^handle_yoauth/', 'core.views.handle_yoauth', name='handle_yoauth'),
    url(r'^logout', 'core.views.logout_view', name='logout'),
)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.validators import RegexValidator
class AccountManager(BaseUserManager):
    def create_user(self, yo_name, password=None):
        if not yo_name:
            raise ValueError('Users must have a Yo account')

        user = self.model(yo_name=yo_name)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, yo_name, password):
        user = self.create_user(yo_name, password)
        user.yo_name = yo_name
        user.is_admin = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser, PermissionsMixin):
    yo_name = models.CharField(max_length=1024, unique=True, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = AccountManager()

    USERNAME_FIELD = 'yo_name'
    REQUIRED_FIELDS = []

    def __unicode__(self):
        return self.yo_name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

core/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import UserCreationForm

from datetime import datetime

from core.models import Account, AccountManager


class AccountForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super(AccountForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Account
		fields = ('yo_name', 'password')

finished/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import UserCreationForm

from datetime import datetime

from core.models import Account, AccountManager
from finished.models import Item

class ItemForm(forms.Form):
    content = forms.CharField(max_length = 1024)

core/views.py
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response, render, redirect
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate
from django.db import IntegrityError, connection, transaction
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse

from finished.models import Item
from core.models import Account
from core.forms import AccountForm

import json
import requests

@login_required
def home(request):
	no_items = False
	try:
		# item_queryset=Item.objects.order_by('id')
		items = Item.objects.all()
	except ObjectDoesNotExist:
		no_items = True
		return render_to_response('core/home.html',{'items':items, 'no_items':no_items}, context_instance=RequestContext(request))
	else:
		# items_unordered = [item.content for item in item_queryset]
		# items = items_unordered[-5:]
		return render_to_response('core/home.html',{'items':items}, context_instance=RequestContext(request))


def handle_yoauth(request):
	yoauth_token = request.GET['yoauth_token']
	url = 'http://yoauth.herokuapp.com/validate'
	payload = {'yoauth_token':yoauth_token}
	r = requests.get(url, params=payload)
	text = json.loads(r.text)
	username = str(text['user']['yo_username'])

	try:
		user = Account.objects.get(yo_name=username)
	except ObjectDoesNotExist:
		user = Account(yo_name=username, password='!')
		user.save()

	user.backend = 'django.contrib.auth.backends.ModelBackend'
	login(request, user)
	url = reverse('home')
	return HttpResponseRedirect(url)


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


def create_account(request):
	if request.POST:
		form = AccountForm(request.POST)
		if form.is_valid():
			form.save()
			user = Account.objects.get(id=form.instance.id)
			pw = user.password
			user.set_password(pw)
			user.save()
			url = reverse('home')
			return HttpResponseRedirect(url) 
		else:
			print form.errors
	else:
		form = AccountForm()
	
	return render_to_response('core/create_account.html', context_instance=RequestContext(request))

fsite/core/views.py
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render_to_response, render, redirect
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.db import IntegrityError, connection, transaction
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from finished.models import Item

def home(request):
	no_items = False
	try:
		item_queryset=Item.objects.order_by('id')

	except ObjectDoesNotExist:
		no_items = True
		return render_to_response('core/home.html',{'items':items, 'no_items':no_items}, context_instance=RequestContext(request))
	else:
		items_unordered = [item.content for item in item_queryset]
		items = items_unordered[-5:]
		return render_to_response('core/home.html',{'items':items}, context_instance=RequestContext(request))


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')

templates/core/create_account.html
{% extends "base.html" %}

{% block title %} FinishedYo | Create Account {% endblock %}

{% block page_header %}Create Account{% endblock page_header %}

{% block content %}
<div class="col-md-3">
    <form method="post" action="{% url 'create_account' %}" role="form">


        {% if form.yo_name.errors %}
        <div class="row">
            <div class="span9 formerror">
                {% for error in form.yo_name.errors %}
                <h5>{{ error|escape }}</h5>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="form-group">
            <label for="id_yo_name">Yo Name:</label>
            <input class="form-control" type="text" name="yo_name" id="id_yo_name"
            {% if form.yo_name.value %}
            value="{{form.yo_name.value}}"
            {% endif %}
            >
        </div>

        {% if form.password.errors %}
        <div class="row">
            <div class="span9 formerror">
                {% for error in form.password.errors %}
                <h5>{{ error|escape }}</h5>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="form-group">
            <label for="id_password">Password: </label>
            <input class="form-control" id="id_password" type="password" name="password" maxlength="100"
            {% if form.password.value %}
            value="{{form.password.value}}"
            {% endif %}
            >
        </div>

        <div class="row">
            <div class="col-md-1">
                <input id="form-submit" class="btn btn-primary btn-submit" type="submit" ></input>
            </div>
        </div>
        {% csrf_token %}
    </form>
    {% endblock %}

templates/core/home.html
{% extends "base.html" %}

{% block content %}
<style>
* {
    background-color: transparent;
}

#id_content {

    height: 100px;
    text-shadow: none;
    font-size: 40px;
    display: block;
    text-transform: none;
    border-radius: 0;
    outline:none;
    -webkit-appearance: none;
    -webkit-user-select: none;
    background-color:transparent;
    border:none;
    box-shadow: none;

}

input:focus{
    outline:none;
    -webkit-appearance: none;
    -webkit-user-select: none;
    background:none;

}

#id_item {

}

#id_highlight {
    font-size: 40px;
    font-weight: bold;
}

a {
    color:purple;
}

li {
    list-style-type: none;
}
.page {
    padding-top: 35px;
    width: 50%;
    margin-right: auto;
    margin-left: auto;
}
</style>

<div class="page">
    <ul style="list-style:none" id="id_item" class="center-block">
       {% for item in items %}
	   <li id="id_highlight" class="center-block" ><a href='/finished/delete_item/{{item.id}}'>{{ item.content }}</a></li>
        {% endfor %}
    </ul>

    <form class="form-inline" method="post" action="{% url 'finished_add_item' %}" role="form">
    <ul>
    <li><input class ="form-control" id="id_content" type="text" name="content" maxlength="500" placeholder = "Add Item" autofocus ></input></li>
</ul>
        {% csrf_token %}
    </form>
</div>

{% endblock content %}

{% block extra_javascript %}

$(document).ready(function(){
    $("#id_item").focus();
    $("#id_highlight").click(function(e){
        e.preventDefault();
        $(this).css('color','red')
    });
    $("a").click(function(){
        $(this).unbind('click')
    });
});
{% endblock %}